-- OpenLedger v0.1 — initial schema + double-entry invariants.
-- Money is integer cents (BIGINT). No floats. (ADR-007)
-- Correctness is the entire credibility surface — the invariants below are
-- enforced in the DATABASE, not the application or UI.

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
CREATE TYPE account_type AS ENUM ('asset', 'liability', 'equity', 'income', 'expense');
CREATE TYPE party_kind   AS ENUM ('customer', 'vendor');
CREATE TYPE doc_state    AS ENUM ('draft', 'posted', 'paid', 'void');

-- ---------------------------------------------------------------------------
-- Chart of accounts (tree via parent_code)
-- ---------------------------------------------------------------------------
CREATE TABLE accounts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT NOT NULL UNIQUE,
    name        TEXT NOT NULL,
    type        account_type NOT NULL,
    parent_code TEXT REFERENCES accounts (code),
    currency    TEXT NOT NULL DEFAULT 'EUR',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Journals + entries + lines (the event log)
-- ---------------------------------------------------------------------------
CREATE TABLE journals (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);

CREATE TABLE journal_entries (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id BIGINT NOT NULL REFERENCES journals (id),
    entry_date DATE NOT NULL,
    memo       TEXT,
    reference  TEXT,
    posted_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE journal_lines (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id   BIGINT NOT NULL REFERENCES journal_entries (id),
    account_id BIGINT NOT NULL REFERENCES accounts (id),
    debit      BIGINT NOT NULL DEFAULT 0,   -- integer cents
    credit     BIGINT NOT NULL DEFAULT 0,   -- integer cents
    CONSTRAINT debit_nonneg  CHECK (debit  >= 0),
    CONSTRAINT credit_nonneg CHECK (credit >= 0),
    -- exactly one side non-zero
    CONSTRAINT one_side CHECK ((debit = 0) <> (credit = 0))
);
CREATE INDEX idx_journal_lines_entry   ON journal_lines (entry_id);
CREATE INDEX idx_journal_lines_account ON journal_lines (account_id);

-- ---------------------------------------------------------------------------
-- Parties / AR / AP
-- ---------------------------------------------------------------------------
CREATE TABLE parties (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       party_kind NOT NULL,
    name       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE invoices (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES parties (id),
    state       doc_state NOT NULL DEFAULT 'draft',
    due_date    DATE,
    total       BIGINT NOT NULL DEFAULT 0,   -- integer cents
    entry_id    BIGINT REFERENCES journal_entries (id),  -- set on post
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE invoice_lines (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT NOT NULL REFERENCES invoices (id),
    description TEXT NOT NULL,
    qty         NUMERIC(20, 4) NOT NULL DEFAULT 1,
    unit_price  BIGINT NOT NULL,             -- integer cents
    amount      BIGINT NOT NULL              -- integer cents
);

CREATE TABLE bills (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id  BIGINT NOT NULL REFERENCES parties (id),
    state      doc_state NOT NULL DEFAULT 'draft',
    total      BIGINT NOT NULL DEFAULT 0,    -- integer cents
    entry_id   BIGINT REFERENCES journal_entries (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE bill_lines (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id     BIGINT NOT NULL REFERENCES bills (id),
    description TEXT NOT NULL,
    qty         NUMERIC(20, 4) NOT NULL DEFAULT 1,
    unit_price  BIGINT NOT NULL,
    amount      BIGINT NOT NULL
);

CREATE TABLE payments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT REFERENCES invoices (id),
    bill_id     BIGINT REFERENCES bills (id),
    amount      BIGINT NOT NULL,             -- integer cents
    account_id  BIGINT NOT NULL REFERENCES accounts (id),
    entry_id    BIGINT REFERENCES journal_entries (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT one_target CHECK ((invoice_id IS NULL) <> (bill_id IS NULL))
);

-- ---------------------------------------------------------------------------
-- Inventory
-- ---------------------------------------------------------------------------
CREATE TABLE items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku        TEXT NOT NULL UNIQUE,
    name       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE locations (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);
CREATE TABLE stock_moves (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id       BIGINT NOT NULL REFERENCES items (id),
    qty           NUMERIC(20, 4) NOT NULL,
    from_location BIGINT REFERENCES locations (id),
    to_location   BIGINT REFERENCES locations (id),
    unit_cost     BIGINT,                    -- integer cents
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Audit + idempotency
-- ---------------------------------------------------------------------------
CREATE TABLE events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor       TEXT NOT NULL,
    capability  TEXT NOT NULL,
    inputs_hash TEXT NOT NULL,
    entity_id   TEXT,
    result_ids  BIGINT[],
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE idempotency_keys (
    operation       TEXT NOT NULL,
    idempotency_key UUID NOT NULL,
    result          JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- A duplicate post is physically impossible: a retried call collides here
    -- and returns the stored result instead of creating a second entry.
    PRIMARY KEY (operation, idempotency_key)
);

-- ===========================================================================
-- INVARIANT 1 — every journal entry balances (>= 2 lines, Σdebit = Σcredit).
-- Deferred constraint trigger: lines may be inserted one at a time within a
-- transaction; the check runs once at COMMIT.
-- ===========================================================================
CREATE OR REPLACE FUNCTION assert_entry_balanced() RETURNS trigger AS $$
DECLARE
    v_entry   BIGINT := COALESCE(NEW.entry_id, OLD.entry_id);
    v_debits  BIGINT;
    v_credits BIGINT;
    v_lines   INT;
BEGIN
    SELECT COALESCE(SUM(debit), 0), COALESCE(SUM(credit), 0), COUNT(*)
      INTO v_debits, v_credits, v_lines
      FROM journal_lines
     WHERE entry_id = v_entry;

    -- Entry may have been fully removed within the tx — nothing to check.
    IF v_lines = 0 THEN
        RETURN NULL;
    END IF;
    IF v_lines < 2 THEN
        RAISE EXCEPTION 'UNBALANCED_ENTRY: entry % has % line(s), need >= 2', v_entry, v_lines;
    END IF;
    IF v_debits <> v_credits THEN
        RAISE EXCEPTION 'UNBALANCED_ENTRY: entry % debits % != credits %', v_entry, v_debits, v_credits;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER trg_entry_balanced
    AFTER INSERT ON journal_lines
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION assert_entry_balanced();

-- ===========================================================================
-- INVARIANT 1b — an entry header must have its balanced lines at COMMIT.
-- The journal_lines trigger above only fires when a LINE is inserted, so a bare
-- `INSERT INTO journal_entries` with no lines would never be checked and would
-- persist a degenerate, unbalanced (empty) entry. This deferred trigger on
-- journal_entries closes that hole: every committed entry must have >= 2 lines
-- with Σdebit = Σcredit, regardless of how it was created.
-- ===========================================================================
CREATE OR REPLACE FUNCTION assert_entry_has_balanced_lines() RETURNS trigger AS $$
DECLARE
    v_debits  BIGINT;
    v_credits BIGINT;
    v_lines   INT;
BEGIN
    SELECT COALESCE(SUM(debit), 0), COALESCE(SUM(credit), 0), COUNT(*)
      INTO v_debits, v_credits, v_lines
      FROM journal_lines
     WHERE entry_id = NEW.id;

    IF v_lines < 2 THEN
        RAISE EXCEPTION 'UNBALANCED_ENTRY: entry % has % line(s), need >= 2', NEW.id, v_lines;
    END IF;
    IF v_debits <> v_credits THEN
        RAISE EXCEPTION 'UNBALANCED_ENTRY: entry % debits % != credits %', NEW.id, v_debits, v_credits;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER trg_entry_has_lines
    AFTER INSERT ON journal_entries
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION assert_entry_has_balanced_lines();

-- ===========================================================================
-- INVARIANT 2 — the ledger + audit log are append-only. No UPDATE / DELETE.
-- Corrections are reversing entries, never edits.
-- ===========================================================================
CREATE OR REPLACE FUNCTION forbid_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'APPEND_ONLY: % on % is forbidden (corrections are reversing entries)',
        TG_OP, TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_je_immutable BEFORE UPDATE OR DELETE ON journal_entries
    FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
CREATE TRIGGER trg_jl_immutable BEFORE UPDATE OR DELETE ON journal_lines
    FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
CREATE TRIGGER trg_ev_immutable BEFORE UPDATE OR DELETE ON events
    FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
