-- OpenERP — fiscal periods + effective (economic) date + period-close lock.
-- Adds the Fowler "whenCharged" (effective_date) date distinct from the booked
-- entry_date and the wall-clock posted_at, and makes posting into a CLOSED
-- fiscal period impossible at the DATABASE level (the credibility surface).
-- Money stays integer cents; this migration adds no money columns.

-- ---------------------------------------------------------------------------
-- Effective (economic) date — which fiscal period an entry belongs to.
-- Distinct from entry_date (booked) and posted_at (wall-clock insert).
-- Backfill existing rows from entry_date, then enforce NOT NULL.
-- ---------------------------------------------------------------------------
ALTER TABLE journal_entries ADD COLUMN effective_date DATE;
UPDATE journal_entries SET effective_date = entry_date WHERE effective_date IS NULL;
ALTER TABLE journal_entries ALTER COLUMN effective_date SET NOT NULL;

-- ---------------------------------------------------------------------------
-- Fiscal periods. Opt-in: a date with no covering period posts freely; only an
-- explicitly CLOSED period blocks. Periods may not overlap.
-- ---------------------------------------------------------------------------
CREATE TYPE period_state AS ENUM ('open', 'closed');

CREATE TABLE fiscal_periods (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       TEXT NOT NULL UNIQUE,            -- e.g. '2026-06'
    start_date DATE NOT NULL,
    end_date   DATE NOT NULL,
    state      period_state NOT NULL DEFAULT 'open',
    closed_at  TIMESTAMPTZ,
    CONSTRAINT period_range CHECK (start_date <= end_date),
    -- No two periods may overlap. Range types support GiST natively — no extension.
    CONSTRAINT period_no_overlap
        EXCLUDE USING gist (daterange(start_date, end_date, '[]') WITH &&)
);

-- ===========================================================================
-- INVARIANT 3 — no posting into a closed period (keyed by effective_date).
-- BEFORE INSERT on journal_entries: if the effective_date falls inside a period
-- whose state is 'closed', reject. Dates outside any period are allowed.
-- Existing entries in a closed period are already immutable via the append-only
-- triggers (migration 0001), so a close is durable.
-- ===========================================================================
CREATE OR REPLACE FUNCTION assert_period_open() RETURNS trigger AS $$
DECLARE
    v_state period_state;
BEGIN
    SELECT state INTO v_state
      FROM fiscal_periods
     WHERE NEW.effective_date BETWEEN start_date AND end_date;

    IF v_state = 'closed' THEN
        RAISE EXCEPTION 'PERIOD_CLOSED: effective_date % falls in a closed fiscal period',
            NEW.effective_date;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_period_open
    BEFORE INSERT ON journal_entries
    FOR EACH ROW EXECUTE FUNCTION assert_period_open();
