-- CoolERP — durable process engine tables.
-- Tracks multi-step business-process instances and their GL postings.

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
CREATE TYPE instance_status AS ENUM ('active', 'completed', 'cancelled');

-- ---------------------------------------------------------------------------
-- Role → account mapping
-- Human-readable role names (matching posting_rule.debit / .credit in YAML)
-- mapped to account codes in the chart of accounts.
-- ---------------------------------------------------------------------------
CREATE TABLE account_roles (
    role         TEXT NOT NULL PRIMARY KEY,
    account_code TEXT NOT NULL REFERENCES accounts (code)
);

INSERT INTO account_roles (role, account_code) VALUES
    ('cash',                '1000'),
    ('accounts_receivable', '1100'),
    ('inventory',           '1200'),
    ('accounts_payable',    '2000'),
    ('tax_payable',         '2100'),
    ('sales_revenue',       '4000'),
    ('cost_of_goods_sold',  '5000');

-- ---------------------------------------------------------------------------
-- Process instances
-- ---------------------------------------------------------------------------
CREATE TABLE process_instances (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process       TEXT            NOT NULL,
    current_state TEXT            NOT NULL,
    status        instance_status NOT NULL DEFAULT 'active',
    reference     TEXT,
    context       JSONB           NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ     NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Process step log (append-only audit trail)
-- ---------------------------------------------------------------------------
CREATE TABLE process_steps_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id  BIGINT NOT NULL REFERENCES process_instances (id),
    from_state   TEXT   NOT NULL,
    to_state     TEXT   NOT NULL,
    capability   TEXT   NOT NULL,
    actor        TEXT   NOT NULL,
    -- No FK to journal_entries: the ledger and process engine are separate bounded
    -- contexts. The engine only writes an entry_id here after post_journal_entry
    -- has successfully committed its own transaction, so referential correctness
    -- is guaranteed by application logic. A DB-level FK across these two contexts
    -- would require the step-log INSERT to run after the ledger commits but within
    -- the same engine transaction, which is impossible when the ledger manages its
    -- own REPEATABLE READ transaction and the engine holds a FOR UPDATE lock.
    entry_id     BIGINT,
    payload      JSONB,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_process_steps_log_instance ON process_steps_log (instance_id);

-- Reuse the forbid_mutation() function already defined in 0001_init.sql.
CREATE TRIGGER trg_process_steps_log_immutable
    BEFORE UPDATE OR DELETE ON process_steps_log
    FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
